// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/hunts": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hunts"
                ],
                "summary": "Lista hunts disponíveis com paginação por cursor",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cursor da página anterior (opaque, retornado em next_cursor)",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Itens por página (padrão 20, máx 100)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ListHuntsResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/hunts/active": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hunts"
                ],
                "summary": "Retorna a sessão de hunt ativa",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ActiveSessionResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/hunts/start": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hunts"
                ],
                "summary": "Inicia uma sessão de hunt",
                "parameters": [
                    {
                        "description": "Payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.StartHuntRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    }
                }
            }
        },
        "/api/v1/hunts/stop": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hunts"
                ],
                "summary": "Para a hunt em andamento",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/health": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.ActiveSessionResponse": {
            "type": "object",
            "properties": {
                "configured_duration_minutes": {
                    "type": "integer"
                },
                "death_count": {
                    "type": "integer"
                },
                "gold_gained": {
                    "type": "integer"
                },
                "hunt_id": {
                    "type": "string"
                },
                "session_id": {
                    "type": "string"
                },
                "started_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "xp_gained": {
                    "type": "integer"
                }
            }
        },
        "dto.HuntResponse": {
            "type": "object",
            "properties": {
                "difficulty": {
                    "type": "string"
                },
                "gold_per_hour": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "recommended_level": {
                    "type": "integer"
                },
                "xp_per_hour": {
                    "type": "integer"
                }
            }
        },
        "dto.ItemSnapshot": {
            "type": "object",
            "properties": {
                "armor": {
                    "type": "integer"
                },
                "attack": {
                    "type": "integer"
                },
                "defense": {
                    "type": "integer"
                },
                "item_id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.ListHuntsResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.HuntResponse"
                    }
                },
                "next_cursor": {
                    "description": "nil = última página",
                    "type": "string"
                },
                "total": {
                    "description": "total de itens nesta página",
                    "type": "integer"
                }
            }
        },
        "dto.SkillSnapshot": {
            "type": "object",
            "properties": {
                "level": {
                    "type": "integer"
                }
            }
        },
        "dto.SnapshotPayload": {
            "type": "object",
            "properties": {
                "equipment": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/dto.ItemSnapshot"
                    }
                },
                "level": {
                    "type": "integer"
                },
                "skills": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/dto.SkillSnapshot"
                    }
                },
                "vocation": {
                    "type": "string"
                }
            }
        },
        "dto.StartHuntRequest": {
            "type": "object",
            "required": [
                "duration_minutes",
                "hunt_id",
                "snapshot"
            ],
            "properties": {
                "duration_minutes": {
                    "type": "integer",
                    "maximum": 360,
                    "minimum": 1
                },
                "hunt_id": {
                    "type": "string"
                },
                "snapshot": {
                    "$ref": "#/definitions/dto.SnapshotPayload"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "RPG Idle — Progression Service",
	Description:      "Gerencia sessões de hunt, simulação de combate e eventos de progressão.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
